// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXis4fqvLLS4OAW2Fv_Pe9bUJidTsoMQM',
    appId: '1:749550140449:web:7e1f4b2cc12f02b60ef760',
    messagingSenderId: '749550140449',
    projectId: 'park-sg',
    authDomain: 'park-sg.firebaseapp.com',
    storageBucket: 'park-sg.firebasestorage.app',
    measurementId: 'G-L8P7NDLTDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMDDDrmC84g8mHr7xmUi9tPA1L00QUTZ4',
    appId: '1:749550140449:android:07b4de11c90bba990ef760',
    messagingSenderId: '749550140449',
    projectId: 'park-sg',
    storageBucket: 'park-sg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjeMeDlj4UICuknYYE-IHfX2L65hRK4F8',
    appId: '1:749550140449:ios:4c117438ea4bde4a0ef760',
    messagingSenderId: '749550140449',
    projectId: 'park-sg',
    storageBucket: 'park-sg.firebasestorage.app',
    iosBundleId: 'com.chandu.parkSg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjeMeDlj4UICuknYYE-IHfX2L65hRK4F8',
    appId: '1:749550140449:ios:4c117438ea4bde4a0ef760',
    messagingSenderId: '749550140449',
    projectId: 'park-sg',
    storageBucket: 'park-sg.firebasestorage.app',
    iosBundleId: 'com.chandu.parkSg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXis4fqvLLS4OAW2Fv_Pe9bUJidTsoMQM',
    appId: '1:749550140449:web:57b0df404c6591180ef760',
    messagingSenderId: '749550140449',
    projectId: 'park-sg',
    authDomain: 'park-sg.firebaseapp.com',
    storageBucket: 'park-sg.firebasestorage.app',
    measurementId: 'G-5J3Z66JSWZ',
  );
}
